### PR TITLE
fix script encoding issue

### LINKED ISSUE #93: Not support immersive-translate 0.8.0
Thanks for your awesome project!

It seems that immersive-translate 0.8.0 is not supported. The floating button doesn't show up.

Other scripts works fine.

ChromeXt version: 3.6.0

### PR DESCRIPTION
**Pull request by cesaryuan**
fix #93.

Tested on my phone, it works. 

**Existing problem:** 
- [ ] not work on `content://` page because `Fetch API cannot load content://media/external/downloads/1000009435. URL scheme "content" is not supported.`

### CODE REVIEW

**Comment by JingMatrix** [comment]
Yes, you are right, that is the problem. Actually, ChromeXt used `fetch` before (at least v3.4):

https://github.com/JingMatrix/ChromeXt/blob/v3.4/app/src/main/assets/editor.js

It won't be perfect if we want to edit the script in the page.
You cannot fetch the script that you just edited.

**Comment by cesaryuan** [comment]
> It won't be perfect if we want to edit the script in the page.

Sorry, as I can see, in my implementation, it doesn't affect the editing of the script. Because that the fetch is executed before the `renderEditor(code)`.

Assuming this does affect script editing, then the previous fixEncoding will also, because they modify `code.textContent` at the same time.

**Comment by JingMatrix** [comment]
You are right, my bad, I didn't check it clearly.
Use this code:
```javascript
   try {    
      code.textContent = await fetch("").then((res) => res.text());
    } catch {
      fixEncoding(code);
    }
```

Combine your commits into one by a forcing push to your branch.

I will accept it you are done.
Thanks for contributing!

**Comment by cesaryuan** [comment]
I am not particularly proficient in operating git, and Files changed looks strange😂. Some modifications were merged from your commits.

**Pull request merged**
